# dependencies for training and pipeline steps compute
name: breast_cancer_training_env
channels:
  - anaconda
  - conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - pandas
  - numpy 
  - azureml-defaults
  - joblib
  - scikit-learn
  - azureml-sdk==1.27.*
